### ISSUE TITLE
Refactor out METRIC_PER_BLOCK to be a function

### ISSUE THREAD

**Issue by gnomadic** [MetricsDAO/core-evm-contracts#15]
Right now the emission rate in all chef's is hardcoded, but it needs to be dynamic based on the remaining supply - Ideally, for example, staking rewards will logarithmically decrease over time so they can run forever based on the remaining supply within the contract.

This ticket does require us to to know the math just yet - a function returning a hard-coded `4` would still be a necessary refactoring

**Comment by jdaly13** [comment]
@gnomadic - can I close this - as I believe I create a setter and getter in the base Chef contract
