### ISSUE TITLE
SPIKE: do we want to reimburse users if they unvote?

### ISSUE THREAD

**Issue by gnomadic** [MetricsDAO/core-evm-contracts#61]
If we do want to reimburse users - then add the code to do that in the costController 

if we do not - then don't and comment in this ticket and close it.

**Comment by gnomadic** [comment]
Also note this ties into the QuestionStateController - because metric will be locked for voting, and if a question is closed, should we reimburse?

**Comment by thermohaline** [comment]
I think for now it would be good to reinburse -- perhaps change this later on. Will wait until we know how/where we store metric with implementing

**Comment by thermohaline** [comment]
We do -- implementing soon
