### ISSUE TITLE
Spike out UUPS Upgradeable Contracts

### ISSUE THREAD

**Issue by gnomadic** [MetricsDAO/core-evm-contracts#8]
https://docs.openzeppelin.com/contracts/4.x/api/proxy

**Comment by gnomadic** [comment]
The output of a spike is not code - the intention is for someone to spend time in our protocol-dev meetup to share their knowledge and learning with the team.

**Comment by ftfdfrancoeur65** [comment]
UUPS is definitely where people are moving towards.

Two main concepts to think about:
Proxy Contract and the Implementation Contract
-  Proxy Contract: basically the never changing address that transactions point to and where the assets sit (if any)

- Implementation: where the proxy delegates calls

Say I want to call mint for a snazzy new Upgradeable NFT project.

I send the transaction TO the Proxy which delegates the `mint` call to the Implementation.

What patterns are there for upgrading the implementation contracts?

Right now there are two leading patterns:
1. Transparent
2. Universal Upgradeable Proxy Standard [read more here](https://eips.ethereum.org/EIPS/eip-1822)
Main difference:
UUPS:
- upgrading is handled by the implementation contract AND there is a separate admin contract

Transparent:
- upgrade and admin logic is handled in the proxy itself

**Comment by ftfdfrancoeur65** [comment]
I can share in our next meeting. I really don't think this decision had to hold us up rn... maybe let's wait until we flesh out some of the governance needs.
